### ISSUE TITLE
Bug in docs code example?

### ISSUE THREAD

**Issue by brucou** [tldraw/signia#49]
Playground (reproduction): https://codesandbox.io/s/sharp-marco-bcrrpj?file=/src/index.js

Source code (mostly taken from the docs):

```js
import { Patch, produceWithPatches, enablePatches } from 'immer'
import { Atom, atom, computed, isUninitialized } from 'signia'
import { Draft } from 'immer'
import { RESET_VALUE, withDiff } from 'signia'

enablePatches()

class ImmerAtom {
    constructor(name, initialValue) {
        this.atom = atom(name, initialValue, {
            // In order to store diffs, we need to provide the `historyLength` argument
            // to the atom constructor. Otherwise it will not allocate a history buffer.
            historyLength: 10,
        })
    }

    update(fn) {
        const [nextValue, patches] = produceWithPatches(this.atom.value, fn)
        this.atom.set(nextValue, patches)
    }
}

let numMapCalls = 0;
function map(source, fn) {
    return computed(
        source.atom.name + ':mapped',
        (prev, lastComputedEpoch) => {
          numMapCalls++;
            // we need to check whether this is the first time we're running
            if (isUninitialized(prev)) {
                // if so, just map over the array and return it
                return source.atom.value.map(fn)
            }

            // this is not the first time we're running, so we need to calculate the diff of the source atom
            const diffs = source.atom.getDiffSince(lastComputedEpoch)
            console.log("diffs", diffs)
            // if there is not enough history to calculate the diff, this will be the RESET_VALUE constant
            if (diffs === RESET_VALUE) {
                // in which case we need to start over
                return source.atom.value.map(fn)
            }

            // we have diffs and a previous value
            const [next, patches] = produceWithPatches(prev, (draft) => {
                // apply the upstream diffs while generating a new set of downstream diffs
                for (const patch of diffs.flat()) {
                    const index = patch.path[0]
                    if (typeof index !== 'number') {
                        // this will be array length changes
                        draft[patch.path[0]] = patch.value
                        continue
                    }
                    if (patch.op === 'add') {
                        if (patch.path.length === 0) {
                            // this is a new item in the array, we need to splice it in and call the map function on it
                            draft.splice(patch.path[0] , 0, fn(patch.value))
                        } else {
                            // one of the existing items in the array has changed deeply
                            // let's call the map function on the new value
                            draft[index] = fn(source.atom.value[index]) 
                        }
                    } else if (patch.op === 'replace') {
                        // one of the existing items in the array has been fully replaced
                        draft[index] = fn(patch.value) 
                    } else if (patch.op === 'remove') {
                        next.splice(index, 1)
                    }
                }
            })

            // withDiff is a helper function that returns a special value that tells Signia to use the
            // provided value and diff
            return withDiff(next, patches)
        },
        {
            historyLength: 10,
        }
    )
}

const names = new ImmerAtom('names', ['Steve', 'Alex', 'Lu', 'Jamie', 'Mitja'])

let numReverseCalls = 0
const reversedNames = map(names, (name) => {
    numReverseCalls++
    return name.split('').reverse().join('')
})

console.log(reversedNames.value) // [ 'evetS', 'xelA', 'uL', 'eimaJ', 'ajtiM' ]
console.log(numReverseCalls, numMapCalls) // 5

names.update((draft) => {
  draft.push('David')
})

names.update((draft) => {
  draft[0] = 'Sunil'
})
names.update((draft) => {
  draft.pop()
})

console.log(reversedNames.value) // [ 'evetS', 'xelA', 'uL', 'eimaJ', 'ajtiM' ]
console.log(numReverseCalls, numMapCalls) // 5
```

Error message:
```
TypeError: Cannot read properties of undefined (reading 'split')
    at eval (https://bcrrpj.csb.app/src/index.js:110:15)

    at eval (https://bcrrpj.csb.app/src/index.js:80:32)

    at Immer.produce (https://bcrrpj.csb.app/node_modules/immer/dist/immer.cjs.development.js:805:20)

    at Immer.produceWithPatches (https://bcrrpj.csb.app/node_modules/immer/dist/immer.cjs.development.js:857:26)

    at _Computed.historyLength [as derive] (https://bcrrpj.csb.app/src/index.js:54:62)

    at _Computed.__unsafe__getWithoutCapture (https://bcrrpj.csb.app/node_modules/signia/dist/Computed.js:84:27)

    at get value [as value] (https://bcrrpj.csb.app/node_modules/signia/dist/Computed.js:105:24)

    at $csb$eval (https://bcrrpj.csb.app/src/index.js:124:27)

    at H (https://codesandbox.io/static/js/sandbox.1ed00784d.js:1:99925)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.1ed00784d.js:1:112676)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.1ed00784d.js:1:123058)

    at c (https://codesandbox.io/static/js/sandbox.1ed00784d.js:1:112291)

    at loadResources (https://bcrrpj.csb.app/index.html:3:2)

    at $csb$eval (https://bcrrpj.csb.app/index.html:9:3)

    at H (https://codesandbox.io/static/js/sandbox.1ed00784d.js:1:99925)

    at K.evaluate (https://codesandbox.io/static/js/sandbox.1ed00784d.js:1:112676)

    at ge.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.1ed00784d.js:1:123058)

    at ge.evaluateModule (https://codesandbox.io/static/js/sandbox.1ed00784d.js:1:122557)

    at https://codesandbox.io/static/js/sandbox.1ed00784d.js:1:319697

    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4333)

    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4086)

    at forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4690)

    at e (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:206)

    at a (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:417)
```

**Comment by ds300** [comment]
Ah yeah you found a bug, this line should be

```diff
- if (patch.path.length === 0)
+ if (patch.path.length === 1)
```

Thank you! ❤️  I'll update the example
