### ISSUE TITLE
Can't use signia-react-jsx jsxImportSource with Vite

### ISSUE THREAD

**Issue by Lippiece** [tldraw/signia#54]
Error:
```
 [vite] Internal server error: Failed to resolve import "signia-react-jsx/jsx-dev-runtime" from "src/main.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/lippiece/projects/odin/odin-waldo/src/main.tsx:15:6
  1  |  "use strict";
  2  |  import { jsxDEV } from "signia-react-jsx/jsx-dev-runtime";
     |                          ^
  3  |  import { StrictMode } from "react";
  4  |  import ReactDOM from "react-dom/client";
      at formatError (file:///home/lippiece/projects/odin/odin-waldo/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41418:46)
      at TransformContext.error (file:///home/lippiece/projects/odin/odin-waldo/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41414:19)
      at normalizeUrl (file:///home/lippiece/projects/odin/odin-waldo/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39706:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransformContext.transform (file:///home/lippiece/projects/odin/odin-waldo/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39840:47)
      at async Object.transform (file:///home/lippiece/projects/odin/odin-waldo/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
      at async loadAndTransform (file:///home/lippiece/projects/odin/odin-waldo/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
```

**Comment by ds300** [comment]
Thanks for the report! ❤️

This was due to a silly mistake in the package.json. A fix should go out in a few minutes.
